-- 코드를 입력하세요
# SELECT FOOD_TYPE, REST_ID, REST_NAME, MAX(FAVORITES) AS FAVORITES
#   FROM REST_INFO FI 
#  WHERE FOOD_TYPE, REST_ID, REST_NAME 
#  GROUP BY FOOD_TYPE 
#  ORDER BY FOOD_TYPE DESC; 
 
 SELECT FOOD_TYPE, (SELECT REST_ID FROM REST_INFO
         WHERE FOOD_TYPE = RI.FOOD_TYPE
         ORDER BY FAVORITES DESC LIMIT 1
       ) AS REST_ID, (SELECT REST_NAME FROM REST_INFO
         WHERE FOOD_TYPE = RI.FOOD_TYPE
         ORDER BY FAVORITES DESC LIMIT 1
       ) AS REST_NAME, 
    MAX(FAVORITES) AS FAVORITES
  FROM REST_INFO RI
 GROUP BY FOOD_TYPE 
 ORDER BY FOOD_TYPE DESC; 
 
# SELECT * 
#   FROM REST_INFO
#  ORDER BY FOOD_TYPE; 