-- 코드를 입력하세요
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES 
  FROM REST_INFO 
 WHERE (FOOD_TYPE, FAVORITES) 
    IN (SELECT FOOD_TYPE, MAX(FAVORITES) FROM REST_INFO GROUP BY FOOD_TYPE)
 GROUP BY FOOD_TYPE 
 ORDER BY FOOD_TYPE DESC; 

# SELECT * FROM REST_INFO 
#  ORDER BY FOOD_TYPE, FAVORITES DESC;

# 한식 은돼지식당 
# 중식 만정 
# 일식 스시사카우스 
# 양식 따띠따
# 분식 애플우스